### PR TITLE
www.e24cloud.com added

### PR DESCRIPTION
**Pull request by r--w**
www.e24cloud.com hosting added

### CODE REVIEW

**Comment by client9** [comment]
I try to re-add this manually

**Comment by SPDNet** [comment]
Unfortunately most of datacenters was not added to the list .but their resellers added for ex.
There is no netdirekt, Salay , DGN ...etc. but there it is their resellers

**Comment by jimdigriz** [comment]
Maybe I am missing something, but only one of these ranges looks associated with e24.  Would be nice to know where this data came from, otherwise all I have to look at are the WHOIS entries.

Many of the entries *are* datacenters, some I am uncomfortable adding to my own list, others...it is too vague to make any conclusion.

**Comment by shawnps** [comment]
@jimdigriz which one in particular did you find to be actually associated with e24? Maybe we can start from there.

**Comment by jimdigriz** [comment]
@shawnps 193.187.64.0/21

**Comment by shawnps** [comment]
@r--w I'm going to pick out the range that @jimdigriz mentioned and credit you with it, then close this out. If you still want the rest of the datacenters added but with updated information, or can let us know where the data comes from that shows these belong to e24cloud, please open up a new PR and I'll take a look.

**Comment by shawnps** [comment]
Thanks @jimdigriz for researching

**Pull request closed without merging**
