### PR TITLE
Use net.LookupTXT instead of dig for AppEngine ips

### PR DESCRIPTION
**Pull request by tmthrgd**
This pull request replaces the use of dig and `exec.Command` with `net.LookupTXT` in `DownloadAppEngine`. This is substantially faster and uses much less memory.

It's also far more reliable as it does not require an external binary and does not parse the output of a command. I also implemented a more rigorous parser of the spf record.

This pull request also adds a test case that simply compares the result against the old implementation, that now exists solely for tests.

Performance numbers are as follows:
```
name                 old time/op    new time/op    delta
DownloadAppEngine-8     2.14s ±19%     1.01s ±50%  -52.69%  (p=0.000 n=18+18)

name                 old alloc/op   new alloc/op   delta
DownloadAppEngine-8     363kB ± 1%      35kB ± 0%  -90.34%  (p=0.000 n=20+18)

name                 old allocs/op  new allocs/op  delta
DownloadAppEngine-8     1.17k ± 0%     0.40k ± 0%  -66.00%  (p=0.000 n=20+17)
```

### CODE REVIEW

**Comment by tmthrgd** [comment]
The travis build <https://travis-ci.org/client9/ipcat/builds/325777963> is failing because the dig command is not available. A possible solution is just to skip this test if dig isn't available. That wouldn't be any worse than before because `DownloadAppEngine` previously had no test case at all.

**Comment by shawnps** [comment]
@tmthrgd thanks for the PR. Let's just remove the references to the `dig` calls and use the `net. LookupTXT`. That way we don't need the tests and benchmarks around the old code.

**Comment by tmthrgd** [comment]
@shawnps So just to clarify, you want me to remove all of `appengine_test.go`?

**Comment by shawnps** [comment]
@tmthrgd I might be missing something, but it looks like those tests assume we're using `dig`, but the new functionality that you wrote would be using `net.LookupTXT`, so the tests wouldn't be testing the actual functionality anymore, right? If that's the case I say just remove the tests, yeah. What do you think?

**Comment by tmthrgd** [comment]
@shawnps `TestDownloadAppEngine` is a regression test, it compares the output of the new and old methods to make sure the results are the same.

It's not strictly needed, and it's very much up to you whether I remove it or not.

**Comment by shawnps** [comment]
@tmthrgd that's okay, using those commands to update the appengine data is a manual process so if anything goes wrong I'll probably notice. Feel free to remove the regression test

**Comment by tmthrgd** [comment]
@shawnps Easy, done.

**Comment by shawnps** [comment]
@tmthrgd thanks!

**Pull request merged**
