### PR TITLE
Add more EU, RU, UA, and US datacenters

### PR DESCRIPTION
**Pull request by thentenaar**

### CODE REVIEW

**Comment by client9** [comment]
Ooh this is a biggie

**Comment by client9** [comment]
I will merge this in manually.  Git is not happy :-(  But I am happy with this patch!!

**Comment by thentenaar** [comment]
It took quite a bit of effort to root these all out, but I'm glad to do so. Enjoy! :P

**Comment by jimdigriz** [comment]
The first two entries (Prisco and Datagroup) are not datacenters.  Prisico supply Internet access to home users...you cannot list an ISP that also happens to provider hosting services.

**Comment by shawnps** [comment]
@thentenaar really appreciate the patch, but since it's a pretty huge diff and there are conflicts, as well as @jimdigriz's concerns, I'll probably hand pick some of these out after doing some research and then close this ticket out. Again thanks for the patch!

**Pull request closed without merging**
